# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: arystan
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: scanner-bot
service: aws-node-vscanner-bot

provider:
  name: aws
  runtime: nodejs20.x
  timeout: 30
  environment:
    DATABASE_URL: ${env:DATABASE_URL}
    MAILGUN_API_KEY: ${env.MAILGUN_API_KEY}

functions:
  api:
    handler: handler.handler
    events:
      - httpApi: "*"
      - schedule: rate(24 hours)